image: docker:18.09.9

services:
  - docker:18.09.9-dind
  
before_script:
  - echo "$CI_REGISTRY_PASSWORD" | docker login --username "$CI_REGISTRY_USER" --password-stdin

r13b:
  stage: build
  variables:
    VERSION: r13b
  script:
    - docker build --pull -t alvisisme/android-ndk:$VERSION --build-arg ANDROID_NDK_VERSION=$VERSION .
    - docker push alvisisme/android-ndk:$VERSION
  only:
    - master
