image: docker:18.09.9

services:
  - docker:18.09.9-dind
  
before_script:
  - echo "$CI_REGISTRY_PASSWORD" | docker login --username "$CI_REGISTRY_USER" --password-stdin

r10e:
  stage: build
  variables:
    VERSION: r10e
  script:
    - docker build --pull -t alvisisme/android-ndk:$VERSION --build-arg ANDROID_NDK_VERSION=$VERSION .
    - docker push alvisisme/android-ndk:$VERSION
  only:
    - master

r11c:
  stage: build
  variables:
    VERSION: r11c
  script:
    - docker build --pull -t alvisisme/android-ndk:$VERSION --build-arg ANDROID_NDK_VERSION=$VERSION .
    - docker push alvisisme/android-ndk:$VERSION
  only:
    - master

r12b:
  stage: build
  variables:
    VERSION: r12b
  script:
    - docker build --pull -t alvisisme/android-ndk:$VERSION --build-arg ANDROID_NDK_VERSION=$VERSION .
    - docker push alvisisme/android-ndk:$VERSION
  only:
    - master

r13b:
  stage: build
  variables:
    VERSION: r13b
  script:
    - docker build --pull -t alvisisme/android-ndk:$VERSION --build-arg ANDROID_NDK_VERSION=$VERSION .
    - docker push alvisisme/android-ndk:$VERSION
  only:
    - master

r14b:
  stage: build
  variables:
    VERSION: r14b
  script:
    - docker build --pull -t alvisisme/android-ndk:$VERSION --build-arg ANDROID_NDK_VERSION=$VERSION .
    - docker push alvisisme/android-ndk:$VERSION
  only:
    - master

r15c:
  stage: build
  variables:
    VERSION: r15c
  script:
    - docker build --pull -t alvisisme/android-ndk:$VERSION --build-arg ANDROID_NDK_VERSION=$VERSION .
    - docker push alvisisme/android-ndk:$VERSION
  only:
    - master

r16b:
  stage: build
  variables:
    VERSION: r16b
  script:
    - docker build --pull -t alvisisme/android-ndk:$VERSION --build-arg ANDROID_NDK_VERSION=$VERSION .
    - docker push alvisisme/android-ndk:$VERSION
  only:
    - master

r17c:
  stage: build
  variables:
    VERSION: r17c
  script:
    - docker build --pull -t alvisisme/android-ndk:$VERSION --build-arg ANDROID_NDK_VERSION=$VERSION .
    - docker push alvisisme/android-ndk:$VERSION
  only:
    - master

r18b:
  stage: build
  variables:
    VERSION: r18b
  script:
    - docker build --pull -t alvisisme/android-ndk:$VERSION --build-arg ANDROID_NDK_VERSION=$VERSION .
    - docker push alvisisme/android-ndk:$VERSION
  only:
    - master

r19c:
  stage: build
  variables:
    VERSION: r19c
  script:
    - docker build --pull -t alvisisme/android-ndk:$VERSION --build-arg ANDROID_NDK_VERSION=$VERSION .
    - docker push alvisisme/android-ndk:$VERSION
  only:
    - master
