services:
  - docker

rvm:
  - 2.5

env:
- NDK_VERSION=r10e
- NDK_VERSION=r11c
- NDK_VERSION=r12b

branches:
  only:
  - master

jobs:
  include:
    - stage: build
      script:
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - docker build --pull -t alvisisme/android-ndk:$NDK_VERSION --build-arg ANDROID_NDK_VERSION=$NDK_VERSION .
        - docker push alvisisme/android-ndk:$NDK_VERSION
