name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  android-ndk:r9d:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build the android-ndk:r9d Docker image
        run: docker build --build-arg="ANDROID_NDK_VERSION=r9d" . --file Dockerfile.r9d --tag alvisisme/android-ndk:r9d
      - name: Push the android-ndk:r9d Docker image
        run: docker push alvisisme/android-ndk:r9d && docker rmi alvisisme/android-ndk:r9d

  android-ndk:r10e:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build the android-ndk:r10e Docker image
        run: docker build --build-arg="ANDROID_NDK_VERSION=r10e" . --file Dockerfile.r10e-r22b --tag alvisisme/android-ndk:r10e
      - name: Push the android-ndk:r10e Docker image
        run: docker push alvisisme/android-ndk:r10e && docker rmi alvisisme/android-ndk:r10e

  android-ndk:r11c:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build the android-ndk:r11c Docker image
        run: docker build --build-arg="ANDROID_NDK_VERSION=r11c" . --file Dockerfile.r10e-r22b --tag alvisisme/android-ndk:r11c
      - name: Push the android-ndk:r11c Docker image
        run: docker push alvisisme/android-ndk:r11c && docker rmi alvisisme/android-ndk:r11c

  android-ndk:r12b:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build the android-ndk:r12b Docker image
        run: docker build --build-arg="ANDROID_NDK_VERSION=r12b" . --file Dockerfile.r10e-r22b --tag alvisisme/android-ndk:r12b
      - name: Push the android-ndk:r12b Docker image
        run: docker push alvisisme/android-ndk:r12b && docker rmi alvisisme/android-ndk:r12b
        
  android-ndk:r13b:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build the android-ndk:r13b Docker image
        run: docker build --build-arg="ANDROID_NDK_VERSION=r13b" . --file Dockerfile.r10e-r22b --tag alvisisme/android-ndk:r13b
      - name: Push the android-ndk:r13b Docker image
        run: docker push alvisisme/android-ndk:r13b && docker rmi alvisisme/android-ndk:r13b

  android-ndk:r14b:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}     
      - name: Build the android-ndk:r14b Docker image
        run: docker build --build-arg="ANDROID_NDK_VERSION=r14b" . --file Dockerfile.r10e-r22b --tag alvisisme/android-ndk:r14b
      - name: Push the android-ndk:r14b Docker image
        run: docker push alvisisme/android-ndk:r14b && docker rmi alvisisme/android-ndk:r14b
                      
  android-ndk:r15c:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}     
      - name: Build the android-ndk:r15c Docker image
        run: docker build --build-arg="ANDROID_NDK_VERSION=r15c" . --file Dockerfile.r10e-r22b --tag alvisisme/android-ndk:r15c
      - name: Push the android-ndk:r15c Docker image
        run: docker push alvisisme/android-ndk:r15c && docker rmi alvisisme/android-ndk:r15c

  android-ndk:r16b:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}                        
      - name: Build the android-ndk:r16b Docker image
        run: docker build --build-arg="ANDROID_NDK_VERSION=r16b" . --file Dockerfile.r10e-r22b --tag alvisisme/android-ndk:r16b
      - name: Push the android-ndk:r16b Docker image
        run: docker push alvisisme/android-ndk:r16b && docker rmi alvisisme/android-ndk:r16b

  android-ndk:r17c:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}    
      - name: Build the android-ndk:r17c Docker image
        run: docker build --build-arg="ANDROID_NDK_VERSION=r17c" . --file Dockerfile.r10e-r22b --tag alvisisme/android-ndk:r17c
      - name: Push the android-ndk:r17c Docker image
        run: docker push alvisisme/android-ndk:r17c && docker rmi alvisisme/android-ndk:r17c

  android-ndk:r18b:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}   
      - name: Build the android-ndk:r18b Docker image
        run: docker build --build-arg="ANDROID_NDK_VERSION=r18b" . --file Dockerfile.r10e-r22b --tag alvisisme/android-ndk:r18b
      - name: Push the android-ndk:r18b Docker image
        run: docker push alvisisme/android-ndk:r18b && docker rmi alvisisme/android-ndk:r18b
        
  android-ndk:r19c:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}  
      - name: Build the android-ndk:r19c Docker image
        run: docker build --build-arg="ANDROID_NDK_VERSION=r19c" . --file Dockerfile.r10e-r22b --tag alvisisme/android-ndk:r19c
      - name: Push the android-ndk:r19c Docker image
        run: docker push alvisisme/android-ndk:r19c && docker rmi alvisisme/android-ndk:r19c

  android-ndk:r20b:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}  
      - name: Build the android-ndk:r20b Docker image
        run: docker build --build-arg="ANDROID_NDK_VERSION=r20b" . --file Dockerfile.r10e-r22b --tag alvisisme/android-ndk:r20b
      - name: Push the android-ndk:r20b Docker image
        run: docker push alvisisme/android-ndk:r20b && docker rmi alvisisme/android-ndk:r20b

  android-ndk:r21e:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }} 
      - name: Build the android-ndk:r21e Docker image
        run: docker build --build-arg="ANDROID_NDK_VERSION=r21e" . --file Dockerfile.r10e-r22b --tag alvisisme/android-ndk:r21e
      - name: Push the android-ndk:r21e Docker image
        run: docker push alvisisme/android-ndk:r21e && docker rmi alvisisme/android-ndk:r21e
        
  android-ndk:r22b:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }} 
      - name: Build the android-ndk:r22b Docker image
        run: docker build --build-arg="ANDROID_NDK_VERSION=r22b" . --file Dockerfile.r10e-r22b --tag alvisisme/android-ndk:r22b
      - name: Push the android-ndk:r22b Docker image
        run: docker push alvisisme/android-ndk:r22b && docker rmi alvisisme/android-ndk:r22b
                
  android-ndk:r23c:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }} 
      - name: Build the android-ndk:r23c Docker image
        run: docker build --build-arg="ANDROID_NDK_VERSION=r23c" . --file Dockerfile.r23c-25c --tag alvisisme/android-ndk:r23c
      - name: Push the android-ndk:r23c Docker image
        run: docker push alvisisme/android-ndk:r23c && docker rmi alvisisme/android-ndk:r23c
                        
  android-ndk:r24:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }} 
      - name: Build the android-ndk:r24 Docker image
        run: docker build --build-arg="ANDROID_NDK_VERSION=r24" . --file Dockerfile.r23c-25c --tag alvisisme/android-ndk:r24
      - name: Push the android-ndk:r24 Docker image
        run: docker push alvisisme/android-ndk:r24 && docker rmi alvisisme/android-ndk:r24
                        
  android-ndk:r25c:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }} 
      - name: Build the android-ndk:r25c Docker image
        run: docker build --build-arg="ANDROID_NDK_VERSION=r25c" . --file Dockerfile.r23c-25c --tag alvisisme/android-ndk:r25c
      - name: Push the android-ndk:r25c Docker image
        run: docker push alvisisme/android-ndk:r25c && docker rmi alvisisme/android-ndk:r25c